### ISSUE TITLE
C version changes the proportion of the image

### ISSUE THREAD

**Issue by PowerSnail** [posva/catimg#12]
![image](https://cloud.githubusercontent.com/assets/7428673/20685859/2b5958ba-b584-11e6-8994-463af8c6c72c.png)

The above is C version and the below is the script version. The script version shows the correct proportion, but the C version makes the image shorter. 

I am using Bash on Windows.

Here is the original image: ![original](https://myanimelist.cdn-dena.com/images/characters/6/275276.jpg)

**Comment by posva** [comment]
I've never tested this on windows. You need a terminal that supports unicode characters. In your pictures it seems to be messed up

**Comment by PowerSnail** [comment]
I tested by using another terminal emulator to ssh onto the Bash On Windows, and everything looks fine. I guess it's probably something weird about Windows' Console.

Thank you for your time.

**Comment by posva** [comment]
Glad you find the solution! 
I'm honestly surprised it works on Windows xD
