### ISSUE TITLE
[INVALID] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [posva/catimg#13]
Dear Eduardo,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by posva** [comment]
@sergeevabc Unfortunately, I don't have a windows to do this. It only requires gcc. Maybe someone can do it with a virtual machine or a windows.
However, I'm not sure it works on windows. It may work on modern terminals inspired by unix systems

**Comment by nurudin-imsirovic** [comment]
I've made a [binary](https://github.com/nurudin-imsirovic/ports-linux/tree/main/c/catimg) on my GitHub repo [ports-linux](https://github.com/nurudin-imsirovic/ports-linux)

Perhaps @posva could link to it in his README.md

Cheers

**Comment by sergeevabc** [comment]
Hmm, someone reported a binary to try in February, but it's already gone, alas.
