### ISSUE TITLE
monochrome Braille images

### ISSUE THREAD

**Issue by kilobyte** [posva/catimg#16]
Here's an idea that might or might not be out of scope for your project:
by abusing the Braille range, it is possible to quadruple the resolution (2x4 pixels per character), at the cost of losing color.  Even tricks we did in ZX-Spectrum days (finding the best ink/paper combination for a whole block) won't work as Braille pixels don't fill their whole space, so only ink can be reasonable changed, and that's probably not worth the effort.

On the other hand, black-and-white images would be useful for emails (esp. signatures), forum posts, etc -- such mediums don't allow colors.

I've did a variant for this for text rather than images in my [braillefont](https://github.com/kilobyte/braillefont).

**Comment by posva** [comment]
Hey, thanks for your interest.

I'd love to increase the resolution but the braille characters doesn't provide enough flexibility or precision to do so with colored images.

**Comment by kilobyte** [comment]
For the record: I've written such a version myself (brailleimg) -- besides drastically higher resolution, it can also be used in mails, forum posts, etc -- all the media that support Unicode but not inline images.

But then, it was pointed out that ImageMagick already can do this: "convert foo.png foo.ubrl", it was just not documented at all.
