### ISSUE TITLE
manpage installs to wrong location

### ISSUE THREAD

**Issue by highvoltage** [posva/catimg#21]
manpage installs to `share/man` instead of `usr/share/man`

**Comment by highvoltage** [comment]
I tried it with catimg 2.3.2 with the improvements, but now it seems to install to `usr/usr/share/man`. If I edit the cmakelists so that `set(MAN_OUTPUT_PATH "usr/share/man/man1")` is changed to `set(MAN_OUTPUT_PATH "share/man/man1")`, then it installs to the correct place.

**Comment by posva** [comment]
I'll have to test again
