### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [posva/catimg#3]
Would you like to add more error handling for [a failed call](https://github.com/posva/catimg/blob/3ed2e75caf9466bb3ec3cf7f788f23496362fca2/src/catimg.c#L71 "Update candidate: main()") of [a function like printf()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.")?

**Comment by posva** [comment]
I'm interested, how can printf fail?

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by posva** [comment]
well, not every error but only errors that can happen. Some errors just never happen and I don't want to complexify the code without getting any value from it

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?

**Comment by posva** [comment]
Maybe but I do not have the knowledge to do it :confused:.
Did catimg failed when you used it ?

**Comment by elfring** [comment]
I would prefer that strict error detection will become less optional in useful software.
Is [the importance of software robustness](https://en.wikipedia.org/w/index.php?title=Robustness_%28computer_science%29 "Making software more robust?") increasing for the affected image viewer?

**Comment by posva** [comment]
not really.
why do you sound as if you were trying to sell me something? It's very suspicious

**Comment by elfring** [comment]
I am just curious if you would like to make your software a bit safer.

**Comment by posva** [comment]
well, that could be great but I think this little piece of software doesn't need that much security

**Comment by elfring** [comment]
I find that every useful software should usually be prepared for exceptional run-time conditions.

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for your software?

Do you find information sources like the following useful?
* Article "[A Reusable Aspect for Memory Allocation Checking](https://web.archive.org/web/20120220075303/http://research.msrg.utoronto.ca/ACC/Tutorial#A_Reusable_Aspect_for_Memory_All "AspectC Tutorial")"
* Document "[Aspect-Oriented Software Development - An Introduction](https://web.archive.org/web/20130512025224/http://www.info.ucl.ac.be/~jbrichau/courses/introductionToAOSD.pdf "AOSD")" by Johan Brichau and Theo D'Hondt
* Paper "[On Typesafe Aspect Implementations in C++](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.125.2164 "AspectC++")" by Daniel Lohmann and Olaf Spinczyk

**Comment by posva** [comment]
thanks for the resources! :)
catimg doesn't need those though

Also the way you write is really weird, it makes me feel very uncomfortable

**Comment by elfring** [comment]
Which communication ways would you prefer to achieve a better comon understanding eventually?

**Comment by posva** [comment]
You don't sound/read human
