### ISSUE TITLE
Incorrect colour output with zsh

### ISSUE THREAD

**Issue by pridyok** [posva/catimg#45]
I installed catimg using brew and added the plugin to oh-my-zsh. It works for the most part but the colours are wrong. I tested it using the test images in the repo and mewtwo looks like this:

<img width="840" alt="Screen Shot 2019-03-14 at 3 48 39 PM" src="https://user-images.githubusercontent.com/5302733/54396570-b9dc1300-4670-11e9-9ead-11820f98cf39.png">

Is there some configuration change I need to make or is this an issue with the oh-my-zsh plugin?

**Comment by posva** [comment]
catimg is an executable, it shouldn't collide with hmz plugins.
You can take a look at your env variables for colors like `$TERM` (I set it to xterm-256color) and `$COLORTERM` (I have truecolor)

If you have tmux I think there are some settings you may need to update if you never changed your configuration
