### ISSUE TITLE
width (-w) handling depending on resolution

### ISSUE THREAD

**Issue by boretom** [posva/catimg#47]
Hi,

I'm playing around with catimg (the c app, not the script) and don't fully understand the width (-w) parameter.

Especially I don't see why setting the resolution to 1 or 2 has an impact on the image width. The terminal width (tput cols) is the same in both scenarios, no? Is it supposed to behave like that?

/Thomas

**Comment by posva** [comment]
the resolution makes one pixel span over two characters or not. then the width uses that count, so -r 1 will produce a larger image. In other words, the width isn't in terms of columns but rather in term of rendered pixels

**Comment by boretom** [comment]
Ok, I see. Thanks for clarifying it ... it's quite confusing but nevermind
