### ISSUE TITLE
Script not working on macos catalina

### ISSUE THREAD

**Issue by homogulosus** [posva/catimg#52]
Distro: OS X 10.15.5
Kernel: Darwin
Terminal: xterm-256color iTerm.app

I have tried the script in bash and zsh and in both shells I have the same results,  a blinking screen repeating the following lines many pages long, the token is the only different part in every line. 
./catimg: line 77: ((: 64.2629%: syntax error: invalid arithmetic operator (error token is ".2629%")
  ./catimg: line 66: [: 63.3999%: integer expression expected
./catimg: line 77: ((: 63.3999%: syntax error: invalid arithmetic operator (error token is ".3999%")

**Comment by posva** [comment]
I tested on the same environment and couldn't reproduce. You seem to be having problem with the expression like this one


```sh
(( IDX = 232 + r * 23 / 255 ))
```

Bash version

```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
```

. The C program is much better though 😉

**Comment by homogulosus** [comment]
I found a script written in go, it isn't as fast as your C program but gets the job done. I like your C file, indeed is fast but the image quality drop is a bit of a problem.
Thanks a lot anyway for the quick response

**Comment by posva** [comment]
what quality drop? the images are better with the C program, they also have the exact same color if your terminal support it

**Comment by homogulosus** [comment]
when I use the C. program the images are pixelated
