### ISSUE TITLE
catimg retired in Fedora repository

### ISSUE THREAD

**Issue by AquaL1te** [posva/catimg#55]
The package is scheduled for [removal](https://src.fedoraproject.org/rpms/catimg/c/ae73079a55affc24bd9b9220442be2ea9a379755?branch=master) because it's 6+ weeks orphaned. 

The original orphaned the package [due to lack of time](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/XAN42RKFTFT35QENDSIL6HF3L4LHDJOX/). I noticed that a [spec file exists in this Git repo](https://github.com/posva/catimg/blob/master/catimg.spec). This spec file contains a newer release than the one in the Fedora repo.

So this leaves me with a few questions.
* Are you aware that this package was orphaned in Fedora?
* If so, are you planning to adopt the package? Since you're actively maintaining a spec file.
* The spec for version catimg 2.6 doesn't seem to build for Fedora 32 on x86_64: https://koji.fedoraproject.org/koji/taskinfo?taskID=50131810
* Does it build for you?

I'm planning to take over the orphaned package. I'll troubleshoot the build errors soon, if I can solve it then I'll take ownership of the package. But I suspect that in the meantime the package will be removed from the repo's already.

**Comment by posva** [comment]
I'm not aware of this and it's not normal. The package is maintained and stable, it doesn't need to get updates every 6 weeks.

I don't use fedora so I cannot even try it but I would appreciate some help for it

> I'm planning to take over the orphaned package. I'll troubleshoot the build errors soon, if I can solve it then I'll take ownership of the package. But I suspect that in the meantime the package will be removed from the repo's already.

If that means you want to take care of the updates of the spec file so `catimg` as it is known today, stays the same, I'm all for it 👍

**Comment by AquaL1te** [comment]
It's due to being orphaned, so no one is responsible for it anymore and therefore scheduled for deletion. It will remain in the repo's as it seems, for F31 and F32. But not be included in the next releases if not maintained. I'll have a look and fix the build errors and get the package approved again in rawhide. Thank you for your reply.

**Comment by posva** [comment]
Thanks! Has it always been orphaned?

**Comment by posva** [comment]
I see, thanks!

**Comment by AquaL1te** [comment]
The package is up for review again: https://bugzilla.redhat.com/show_bug.cgi?id=1878514
Once that is complete I'll request ownership of the package.

I also [updated the spec file](https://fedorapeople.org/cgit/keesdejong/public_git/rpmbuild.git/tree/SPECS/catimg.spec), are the dependencies still correct? Mainly the cmake >= 2.8.

**Comment by posva** [comment]
Yes, that's correct. It does work with cmake 3 but needs at least that version

**Comment by AquaL1te** [comment]
The updates will appear in the Fedora branches in the next few days. Here's the [overview](https://src.fedoraproject.org/rpms/catimg). And the [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1878514) where information updates will appear.
