### ISSUE TITLE
Please support GCC10

### ISSUE THREAD

**Issue by highvoltage** [posva/catimg#56]
Hi, I maintain catimg in Debian, where we're planning to migrate to gcc10.

According to this bug report, catimg doesn't currently build in gcc10:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=957066

Please support compilation under gcc10 as well.

**Comment by posva** [comment]
Apparently https://github.com/posva/catimg/commit/5e096faa751b8f4eef04ccae923c9aa344dd2e9d fixed the issue. I will tag a new version
