### ISSUE TITLE
piping catimg doesn't properly work

### ISSUE THREAD

**Issue by xproot** [posva/catimg#66]
piping catimg to any other app gives ^[[s^[[?25l^[[?25h

**Comment by posva** [comment]
that's the escape codes for the colors

**Comment by 7coil** [comment]
This might be because there isn't a tty for `catimg` to grab the terminal width; setting it yourself with the `-w` flag seems to output what I needed.

![image](https://user-images.githubusercontent.com/13886925/148548531-4388a975-b41b-40af-a32e-3c43dec2273e.png)
