### ISSUE TITLE
Images do not properly scale vertically

### ISSUE THREAD

**Issue by acxz** [posva/catimg#67]
Whenever I specify the `-H` flag scale with the height of my image. The complete image does not get shown. Like so:
![2022-02-27-161936_514x596_scrot](https://user-images.githubusercontent.com/17132214/155900329-b445a1eb-7af0-487f-b87d-13df7e5fff29.png)

This is more apparent when displaying gifs. Even with the `-H` flag, when displaying gifs since the gif is not scaled correctly, a jarring artifact can be noticed.

**Comment by acxz** [comment]
I realized the reason the scaling seems to be not working is because my prompt gets displayed immediately after, pushing the image/gif displayed up.

**Comment by posva** [comment]
This is indeed expected behavior. You can still specify a specific value for `-H` to match your custom height.

**Comment by acxz** [comment]
For anyone else coming across this issue I have found another library that handles this issue properly: 
[timg](https://github.com/hzeller/timg)
I have switched to using timg, and recommend other users to do the same.
Sorry if this comes off as a bit aggressive but just wanted to provide a solution/workaround for other users to this issue.
