### ISSUE TITLE
Suggestion: Allow images to be piped in via stdin

### ISSUE THREAD

**Issue by sbrl** [posva/catimg#9]
If I could pipe images in via stdin, then I could do something like this:

```
curl -L https://example.com/image.png | catimg
```

and the image wouldn't have to touch the disk at all.

**Comment by posva** [comment]
![](http://media4.giphy.com/media/QlGxDPQ8ZBO0g/giphy.gif)

**Comment by sbrl** [comment]
?

**Comment by return** [comment]
Assuming you are using the bash version of catimg, piping to bash using curl is a security risk and it is therefore considered bad practice. Several [websites] (https://www.seancassidy.me/dont-pipe-to-your-shell.html) discuss this issue in more [detail.] (https://www.djm.org.uk/protect-yourself-from-non-obvious-dangers-curl-url-pipe-sh/)

**Comment by posva** [comment]
@sbrl That's weird. I never wrote that comment... I was sleeping 6 hours ago.

**Comment by posva** [comment]
Piping was something I thought some time ago but never took the time to implement. The C version may implement this. PR are welcome

**Comment by sbrl** [comment]
@posva That's weird. Maybe you should change your account password and revoke all tokens? Perhaps someone has gained unauthorised access to your account.

@return Right. I didn't know about that! I'll be more careful in future, but I think that it should be ok in this instance since `catimg` won't be executing any of the returned output, so long as `catimg` doesn't have any security issues.

**Comment by posva** [comment]
@sbrl yeah, I revoked almost everything :/
I'll try to give it a look when I get some free time for it

**Comment by posva** [comment]
I still haven't got the time for this. I added the help wanted tag so that people know that PRs are welcome :smile:

**Comment by sbrl** [comment]
@posva I'm just learning c++, so I'd help if it was c++ or if there's a good guide out there that explains the differences so that I don't get confused.

**Comment by posva** [comment]
Oh, don't worry, it doesn't have to be you :smile:. There's a lot of help around the C language. It has been around for a long time

**Comment by sbrl** [comment]
@posva It's precisely that it's been around for a long time that makes it so confusing :(

**Comment by LuRsT** [comment]
@sbrl @return The user is the one who should be concerned about that, not the app.

:+1: To this feature request

**Comment by posva** [comment]
@LuRsT Still very busy. I'm willing to look at this next weekend if nobody creates a PR. But I don't think I'll be able to finish the job

**Comment by LuRsT** [comment]
@posva no worries mate, this is open source software, you do it whenever *you* want to, I didn't mean to push it for you to do it :smile:

**Comment by posva** [comment]
@LuRsT my answer was a bit too cold. I was missing some emoji :laughing: 
I'm actually happy to see people +1 feature requests! I just wanted to make an update on the progress (none) :sweat_smile:

**Comment by LuRsT** [comment]
@posva Hahah I got it :smile: don't worry! I would help but my C knowledge is lacking, here's hoping someone will step up and do this :shipit:

**Comment by mrhmouse** [comment]
I currently do something like this to view images without touching disk:

    catimg <(curl -L https://example.com/example.png)
